### ISSUE TITLE
Decryption is not working on some machines

### ISSUE THREAD

**Issue by 110mat110** [ismetertekin/Ford-Sync2-MirrorLink-VideoPlayer-Navitel#2]
I have problem with decrypt command on 2 laptops. Both of them have Intel CPU, and Nvidia GPU. Command end with error 80090005 Wrong data. On the other hand, on desktop with AMD CPU and no GPU it runs and return result files.

I guess that it is an issue with some kind decrypt library that is not working correctly on Intel CPU

**Comment by ismetertekin** [comment]
Tested on Intel and AMD processors. No problem.
