### ISSUE TITLE
Sync 2

### ISSUE THREAD

**Issue by YuriShef** [ismetertekin/Ford-Sync2-MirrorLink-VideoPlayer-Navitel#3]
Hello, I have a question about activating MirrorLink and Video Player.
  after renaming the file in the installation, it does not happen, the download does not start.  help me figure it out please.

**Comment by YuriShef** [comment]
Not work this is program

**Comment by ismetertekin** [comment]
The application works flawlessly. In some vehicles only mirrorlink works. Just create a file with mirrorlink and try.

**Comment by YuriShef** [comment]
the file that is the wallpaper is loaded, the system reboots the system.  After the reboot, I rename the file to install, nothing happens on one machine, a window appears on others.![image](https://user-images.githubusercontent.com/105967853/170285054-641c9381-9c44-4ba9-b5a8-0add5cc1b86a.jpeg)![Uploading 170285088...]

**Comment by YuriShef** [comment]
![image](https://user-images.githubusercontent.com/105967853/170285503-1e17ad28-fd94-4c02-b941-170acb63a4dd.jpeg)

**Comment by andreyzer0** [comment]
> the file that is the wallpaper is loaded, the system reboots the system. After the reboot, I rename the file to install, nothing happens on one machine, a window appears on others.

получилось решить проблему? я просто вставил в другой порт и началась установка, но у меня не запускаются приложения ничего не происходит при нажатии на них и перезагрузка не работает, сброс Синка не помог, не могу даже удалить эти приложения

**Comment by YuriShef** [comment]
Нет, не могу запустить инсталляцию
