### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by ipekali1970** [ismetertekin/Ford-Sync2-MirrorLink-VideoPlayer-Navitel#4]
Selam, Seri no yazıp uygulamayı çalıştırdığımda unknown error mesajı alıyorum.

**Comment by jurisklevo** [comment]
bende de aynı sorun var

**Comment by Fusion999** [comment]
I have the same problem, can you please help/advise? Screenshot attached
![S](https://user-images.githubusercontent.com/109908869/180650615-d4f06e59-cd57-43a6-a497-1807fb77a052.PNG)

**Comment by ismetertekin** [comment]
> Selam, Seri no yazıp uygulamayı çalıştırdığımda unknown error mesajı alıyorum.

Seçtiğiniz dizine yazma yetkisinden kaynaklanıyor olabilir. Masaüstünü seçip deneyiniz.

**Comment by ismetertekin** [comment]
> I have the same problem, can you please help/advise? Screenshot attached ![S](https://user-images.githubusercontent.com/109908869/180650615-d4f06e59-cd57-43a6-a497-1807fb77a052.PNG)

It may be due to the write permission to the directory you selected. Try the desktop.

**Comment by Fusion999** [comment]
> > I have the same problem, can you please help/advise? Screenshot attached ![S](https://user-images.githubusercontent.com/109908869/180650615-d4f06e59-cd57-43a6-a497-1807fb77a052.PNG)
> 
> It may be due to the write permission to the directory you selected. Try the desktop.

I've tried both: 
1. I have extracted Release-v2.zip folder to the desktop
2. Created New Folder on the desktop
3. Selected this New Folder as a file path while running .exe file
4. Same result - unknown error

5. I've tried the same from another laptop too, didn't succeed :(

**Comment by Fusion999** [comment]
> > > I have the same problem, can you please help/advise? Screenshot attached ![S](https://user-images.githubusercontent.com/109908869/180650615-d4f06e59-cd57-43a6-a497-1807fb77a052.PNG)
> > 
> > 
> > It may be due to the write permission to the directory you selected. Try the desktop.
> 
> I've tried both:
> 
> 1. I have extracted Release-v2.zip folder to the desktop
> 2. Created New Folder on the desktop
> 3. Selected this New Folder as a file path while running .exe file
> 4. Same result - unknown error
> 5. I've tried the same from another laptop too, didn't succeed :(

An update: I've tried from third (!) PC the same steps and the issue was resolved! No idea how, but I'm glad anyway.

**Comment by Mat21-cloud** [comment]
Extrac the file by 7-zip
